version: 2.1

executors:
  default:
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    environment:
      - BUNDLE_JOBS: 4
      - BUNDLE_RETRY: 3
      - BUNDLE_PATH: vendor/bundle
    working_directory: ~/boilerplate-rails-api

jobs:
  checkout:
    executor: default
    steps:
      - checkout
      - run: cp config/database.yml.ci config/database.yml
      - persist_to_workspace:
          root: ~/boilerplate-rails-api
          paths:
            - .

  bundle:
    executor: default
    steps:
      - attach_workspace:
          at: ~/boilerplate-rails-api
      - restore_cache:
          keys:
            - boilerplate-rails-api-{{ checksum "Gemfile.lock" }}
            - boilerplate-rails-api-
      - run: gem i bundler -v $(tail -1 Gemfile.lock | tr -d ' ')
      - run: |
          bundle check || bundle install --frozen --path vendor/bundle && bundle clean
      - save_cache:
          key: boilerplate-rails-api-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/boilerplate-rails-api
          paths:
            - vendor/bundle

  lefthook:
    executor: default
    steps:
      - attach_workspace:
          at: ~/boilerplate-rails-api
      - run: sudo apt-get install cmake
      - run: |
          echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
          source $BASH_ENV
          gem install bundler
      - run: bundle install
      - run: |
          bundle exec lefthook run all

  rspec:
    executor: default
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
      - image: circleci/postgres:11-alpine-ram
        environment:
          - POSTGRES_USER: boilerplate
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/boilerplate-rails-api
      - run: |
          echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
          source $BASH_ENV
          gem install bundler
      - run: yarn
      - run: bundle exec rake db:create db:schema:load --trace
      - run: bundle exec rspec

  yarn:
    executor: default
    steps:
      - attach_workspace:
          at: ~/boilerplate-rails-api
      - restore_cache:
          keys:
            - yarn-v1-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-v1-{{ arch }}-{{ .Branch }}-
            - yarn-v1-
      - run: |
          yarn install --frozen-lockfile
      - save_cache:
          key: yarn-v1-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/boilerplate-rails-api
          paths:
            - node_modules

workflows:
  version: 2
  default: &default
    jobs:
      - checkout
      - bundle:
          requires:
            - checkout
      - yarn:
          requires:
            - checkout
      - rspec:
          requires:
            - yarn
            - bundle
      - lefthook:
          requires:
            - bundle
